### ISSUE TITLE
Uncaught TypeError as line 46 in /var/www/html/vendor/silverstripe/environmentcheck/src/Checks/SolrIndexCheck.php implode(): Argument #2 ($array) must be of type ?array, string given in GET /health/check

### ISSUE THREAD

**Issue by Veronica-davidraj** [silverstripe/silverstripe-environmentcheck#85]
Running this module on;

PHP 8
Docker

Could it be fixed by changing line 46 of SolrIndexCheck.php?

 from 

                'The following indexes are unavailable: ' . implode($brokenCores ?? '', ', ')

to 

                'The following indexes are unavailable: ' . implode(',', $brokenCores ?? '')

is this the right approach ?

**Comment by michalkleiner** [comment]
Thanks for reporting the issue, would you be keen on sending a pull request?
Is the issue with a 2.6 version or the 3.0.0-beta?

**Comment by maxime-rainville** [comment]
This looks like a problem in both CMS4 and CMS5.

https://github.com/silverstripe/silverstripe-environmentcheck/blob/56b37530d68b4aa90f7b3d655cf5c829916ca1dc/src/Checks/SolrIndexCheck.php#L46

**Comment by Veronica-davidraj** [comment]
> 2.6



> Thanks for reporting the issue, would you be keen on sending a pull request? Is the issue with a 2.6 version or the 3.0.0-beta?

The issue is identified in Silverstripe 4.11.0

**Comment by GuySartorelli** [comment]
PR merged and tagged at [2.7.1](https://github.com/silverstripe/silverstripe-environmentcheck/releases/tag/2.7.1)

**Comment by michalkleiner** [comment]
Fix merged up and [3.0.1](https://github.com/silverstripe/silverstripe-environmentcheck/releases/tag/3.0.1) also tagged.
